name: Cache NPM and Composer Weekly
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cache-composer:
    name: Cache Composer with PHP 8.1
    uses: KenTandrian/workflows/.github/workflows/cache-composer.yml@main
    with:
      php-version: 8.1

  cache-node:
    name: Cache with Node.js 18.x
    uses: KenTandrian/workflows/.github/workflows/cache.yml@main
    with:
      caches: node
      package-manager: yarn
